sudo: false
language: node_js
matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: JOB_PART=lint
    - os: linux
      node_js: "6"
      env: JOB_PART=test
    - os: linux
      node_js: "8"
      env: JOB_PART=test
    - os: linux
      node_js: "10"
      env: JOB_PART=test
    - os: linux
      node_js: "11"
      env: JOB_PART=test
before_install:
  - nvm --version
  - node --version
script:
  - npm run travis:$JOB_PART
